# Generated by Django 4.0.7 on 2022-12-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
