# Generated by Django 4.0.7 on 2022-12-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_profile_bio_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio_summary',
            new_name='short_bio',
        ),
    ]
