# Generated by Django 4.0.7 on 2022-08-12 02:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=wagtail.fields.RichTextField(),
        ),
    ]
