# Generated by Django 4.0.7 on 2022-08-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_approval_date_article_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='approval_date',
            new_name='to_be_approved_date',
        ),
    ]
