# Generated by Django 4.0.7 on 2022-08-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_approval_date_article_to_be_approved_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pretext',
            new_name='prologue',
        ),
        migrations.RemoveField(
            model_name='article',
            name='to_be_approved_date',
        ),
        migrations.AddField(
            model_name='article',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date approved for publishing'),
        ),
        migrations.AddField(
            model_name='article',
            name='needs_approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date done writing'),
        ),
        migrations.AlterField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved for publishing'),
        ),
        migrations.AlterField(
            model_name='article',
            name='needs_approval',
            field=models.BooleanField(default=False, verbose_name='done writing'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
    ]
