# Generated by Django 4.0.7 on 2022-08-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_author_alter_article_prologue'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'normal'), (2, 'high'), (3, 'highest')], default=1),
        ),
    ]
