# Generated by Django 4.0.7 on 2022-09-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_infoimage_alter_article_author_infoimagerendition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='infoimagerendition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='infoimagerendition',
            name='image',
        ),
        migrations.DeleteModel(
            name='InfoImage',
        ),
        migrations.DeleteModel(
            name='InfoImageRendition',
        ),
    ]
