# Generated by Django 4.0.7 on 2022-09-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('articles', '0008_alter_infoimagerendition_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.infoimage'),
        ),
    ]
