# Generated by Django 4.0.7 on 2022-09-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prologue',
            field=models.TextField(blank=True),
        ),
    ]
