# Generated by Django 4.0.7 on 2025-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_url_encoded_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('UNA', 'unassigned'), ('SCT', 'at scitech'), ('PIT', 'in pittsburgh'), ('POL', 'politics'), ('TEC', 'technology'), ('SPT', 'sports'), ('POP', 'pop culture'), ('EDT', 'editorial'), ('BLG', 'blog')], default='UNA', max_length=3),
        ),
    ]
